### ISSUE TITLE
prep for presentation

### ISSUE THREAD

**Issue by sabbyt** [AaronFilson/preps#111]
- Explain the challenges that arose during project week and how your team overcame them.

Your presentations should take approx. 15 minutes:

Every team member needs to talk!
- Tell us about what you contributed to the project.
- Tell us about at least one thing you found challenging, and one thing you really enjoyed working on. 

Plan your presentations:
- Who will give an intro, and tell us about the theme of your project?
- Who will talk about the functionality, and walk us through the app?
- Who will show us the code? 

Rehearse your presentation:
- Decide who’s machine will present the app on the projector, test it, and then test a second computer.
- Set a timer and take turns talking through your topics. Know how much time each segment will take.
- Have one team member track time, and help keep things moving forward. 

Expect and be ready to answer questions at the end of your presentation.

**Comment by AaronFilson** [comment]
And done!
