### ISSUE TITLE
PAGE 2: 3.2 User Input (Part 1)

### ISSUE THREAD

**Issue by sabbyt** [AaronFilson/preps#19]
PAGE 2: 3.2 User Input (Part 1)

Part 2: 3.2.1 Local storage

**Comment by AaronFilson** [comment]
Starting off with a drop down menu, and allowing multiple selections

**Comment by AaronFilson** [comment]
Changed to different approach, using separate checkboxes now. Have a box for house, apartment, driving, and medication.

**Comment by AaronFilson** [comment]
I have the user able to check and uncheck boxes to select from 4 options of checklists. Closing.
